# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppLds <- function(z, data, beta) {
    .Call('_idld_cppLds', PACKAGE = 'idld', z, data, beta)
}

cppLdaux <- function(W, proyecciones, beta) {
    .Call('_idld_cppLdaux', PACKAGE = 'idld', W, proyecciones, beta)
}

cppLdaux2 <- function(W, proyecciones, beta, q) {
    .Call('_idld_cppLdaux2', PACKAGE = 'idld', W, proyecciones, beta, q)
}

eigenMatMult <- function(A, B) {
    .Call('_idld_eigenMatMult', PACKAGE = 'idld', A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call('_idld_eigenMapMatMult', PACKAGE = 'idld', A, B)
}

